[package]
name = "simple_window_and_button"
version = "0.1.0"
authors = ["Marcus Belfort<marvinbelfort@gmail.com>"]
edition = "2018"

[dependencies]
bindings = { path = "bindings" }
windows = "*"


[build-dependencies]
bindings = { path = "bindings" }
windows = "*" 